version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/app 
    ports:
      - "8000:8000" 
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
